const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'index.html'),'utf8');
const start=html.indexOf('function publicationValidationErrors('),end=html.indexOf('async function publishRegistrationConfig(',start);
assert(start>=0&&end>start);
const c={state:{meta:{},cloudCode:null},canCreateOfficialTournament:()=>true};vm.createContext(c);vm.runInContext(html.slice(start,end),c);
const onsite={name:'現場賽',date:'2026-09-12',location:'台南',registrationEnabled:false};
assert.equal(c.publicationValidationErrors(onsite).length,0);
assert.equal(c.publicationValidationErrors({...onsite,registrationEnabled:true}).length,3);
assert.equal(c.publicationValidationErrors({...onsite,location:''}).length,1);
assert.equal(c.publicationValidationErrors({...onsite,registrationEnabled:true,registrationOpenAt:100,registrationCloseAt:200,registrationCapacity:16}).length,0);
assert(c.publicationValidationErrors({...onsite,registrationEnabled:true,registrationOpenAt:200,registrationCloseAt:100,registrationCapacity:16}).length>0);
assert(c.renderTournamentPublishAction(false).includes('完成架構並發布'));
assert.equal(c.renderTournamentPublishAction(true),'');
c.state.cloudCode='ROOM';c.state.meta.publishedAt=1;
assert(c.renderTournamentPublishAction(false).includes('更新並重新發布'));
c.state.cloudCode=null;c.canCreateOfficialTournament=()=>false;
assert(c.renderTournamentPublishAction(false).includes('disabled'));
const pageStart=html.indexOf('function renderDailyCheckInPage('),pageEnd=html.indexOf('function renderDailyCheckInCard(',pageStart);
c.safeEngagementRender=()=>'<div>連線錯誤</div>';c.renderDailyCheckInCard=()=>'';
vm.runInContext(html.slice(pageStart,pageEnd),c);
assert(c.renderDailyCheckInPage().includes('data-tab="home"'));
assert(c.renderDailyCheckInPage().includes('連線錯誤'));
assert(html.includes('const APP_VERSION = "v13.29.7"'));
console.log('PASS: onsite and online publication validation; publish/re-publish/permission/read-only actions; return navigation on error; version .7');
